[Eth]
NetworkId = 31337
SyncMode = "fast"
DiscoveryURLs = []
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
DatabaseCache = 512
DatabaseFreezer = ""
TrieCleanCache = 256
TrieCleanCacheJournal = "triecache"
TrieCleanCacheRejournal = 3600000000000
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 0
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""
RPCGasCap = 25000000
RPCTxFeeCap = 1e+00

[Eth.Miner]
GasFloor = 8000000
GasCeil = 8000000
GasPrice = 1000000000
Recommit = 3000000000
Noverify = false

[Eth.Ethash]
CacheDir = "ethash"
CachesInMem = 2
CachesOnDisk = 3
CachesLockMmap = false
DatasetDir = "/Users/alessiobianchini/Library/Ethash"
DatasetsInMem = 1
DatasetsOnDisk = 2
DatasetsLockMmap = false
PowMode = 0

[Eth.TxPool]
Locals = []
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60
MaxPrice = 500000000000

[Node]
DataDir = "/Users/alessiobianchini/Library/Ethereum"
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 22000
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["admin", "eth", "debug", "miner", "net", "txpool", "personal", "web3"]
WSHost = ""
WSPort = 8546
WSModules = ["net", "web3", "eth"]
GraphQLVirtualHosts = ["localhost"]

[Node.P2P]
MaxPeers = 50
NoDiscovery = true
BootstrapNodes = ["enode://a32f04eadc4d18eca8d21ef7c29957b4b777b31d66f03a847aa60b018ae3ef06fbe4bb06899e6260e2795e2533b774b95444f5b99db8c21f045ba6ce6cca2f5f@127.0.0.1:21000?discport=0&raftport=50000"]
BootstrapNodesV5 = ["enode://a32f04eadc4d18eca8d21ef7c29957b4b777b31d66f03a847aa60b018ae3ef06fbe4bb06899e6260e2795e2533b774b95444f5b99db8c21f045ba6ce6cca2f5f@127.0.0.1:21000?discport=0&raftport=50000"]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":21000"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000
